apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: $KUBECONF_CLUSTER_CERTIFICATE_AUTHORITY_DATE
    server: $KUBECONF_SERVER
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: $KUBECONF_USER_NAME
  user:
          client-certificate-data: $KUBECONF_CLIENT_CERTIFICATE_DATA
    client-key-data: $KUBECONF_CLIENT_KEY_DATA
